### ISSUE TITLE
-3^(1*2) wrong result

### ISSUE THREAD

**Issue by karagiannisgithub** [bugwheels94/math-expression-evaluator#64]
It returns -6. It should return -9.
Also -3^(1+1) returns -4. It should return -9. But 0-3^(1+1) return correct answers. (The same for the first example)

**Comment by bugwheels94** [comment]
-3^(1*2) should be returning 9 and i have fixed it. Thanks for informing!

**Comment by karagiannisgithub** [comment]
I think the problem remains (in version 2.0.1):
-3^2 = -9 [right]
-3^(1+1) = -4 [wrong]
-3^(1*2) = -6 [wrong]

**Comment by bugwheels94** [comment]
working fine here: https://jsbin.com/romatuc/edit?html,output 

Make sure that you actually are on 2.0.1

**Comment by karagiannisgithub** [comment]
In school we learn (-3)^2=9 and -3^2=-(3^2)=-9. I understand that you want the unary operator '-' to have a bigger priority than operator '^', but it is not something that we find frequently. If you keep this convention, look the problem: All of us know that a-b=a+(-b), so 9-3^2=9+(-3^2) and although the two previous expressions are equal, your script evaluates the first expression to 0 and the second to 18. Check it.
(I am a mathematician with a master in information systems)

**Comment by bugwheels94** [comment]
I am no mathematician ^_^ but I agree with you. May you try now at version 2.0.2. Actually, the second last message with -4, -6 got me confused a bit. This change is passing all of the tests but I hope it does not break anything
